/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_alpha_demo_jni_Hello */

#ifndef _Included_com_alpha_demo_jni_Hello
#define _Included_com_alpha_demo_jni_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_alpha_demo_jni_Hello
 * Method:    getServerUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_alpha_demo_jni_Hello_getServerUrl
  (JNIEnv *, jclass);

/*
 * Class:     cn_alpha_demo_jni_Hello
 * Method:    getIMGUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_alpha_demo_jni_Hello_getIMGUrl
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
